### ISSUE TITLE
ess not found in Ultranest results

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/jaxns-cosmology#3]
@rruizdeaustri the 'ess' key is not in Ultranest's result object. I'm using Ultranest 4.1.6. Error is at this line: https://github.com/Joshuaalbert/jaxns-cosmology/blob/main/jaxns_cosmology/ultranest_sampler.py#L292

```
    file.write("ESS={}".format(int(out["ess"])))
KeyError: 'ess'
```

**Comment by rruizdeaustri** [comment]
@Joshuaalbert Hmmm, this is weird since I have exactly that version !

If I run the 2D eggbox problem using using the number of live points = 0 which activates the dynamic sampling I get the out dictionary as this: Overwriting tests/ultra_ultranest_EggBox/ with /tmp/tmph9uagr0j/
{'niter': 7208, 'logz': 235.73013207476941, 'logzerr': 0.14550766158689532, 'logz_bs': 235.73465991111433, 'logz_single': 235.73013207476941, 'logzerr_tail': 0.009932890089828561, 'logzerr_bs': 0.14516823783097266, 'ess': 2241.015339557988, 'H': 6.263588654308535, 'Herr': 0.06676658637583711, 'posterior': {'mean': [15.497278367540725, 15.582094400944563], 'stdev': [9.49896132333627, 9.306711719627694], 'median': [12.71188811853195, 12.76499865840651], 'errlo': [6.205999624018651, 6.223904930127239], 'errup': [25.19240909446444, 25.1789061729941], 'information_gain_bits': [2.0988663713247955, 2.0714257387361408]}, 'weighted_samples': {'upoints': array([[9.96991885e-01, 4.04873680e-01],
       [1.95240836e-01, 4.03663272e-01],
       [8.07931739e-01, 6.01740787e-01],
       ...,
       [2.00028054e-01, 6.00002177e-01],
       [4.00004572e-01, 2.07398834e-05],
       [7.99980036e-01, 3.99998254e-01]]), 'points': array([[3.13214238e+01, 1.27194818e+01],
       [6.13367177e+00, 1.26814557e+01],
       [2.53819242e+01, 1.89042444e+01],
       ...,
       [6.28406664e+00, 1.88496243e+01],
       [1.25665142e+01, 6.51562652e-04],
       [2.51321140e+01, 1.25663158e+01]]), 'weights': array([2.08099530e-105, 2.08152997e-105, 2.11737886e-105, ...,
       1.79210064e-005, 1.79213115e-005, 1.79213558e-005]), 'logw': array([ -6.32882951,  -6.33061522,  -6.33240094, ..., -18.19936536,
       -18.19936536, -18.19936536]), 'bootstrapped_weights': array([[3.07922239e-105, 3.17117855e-105, 3.07607155e-105, ...,
        2.98237999e-105, 3.57230128e-105, 3.07958993e-105],
       [0.00000000e+000, 3.16854455e-105, 3.07373920e-105, ...,
        2.98030165e-105, 3.56950794e-105, 3.07732675e-105],
       [0.00000000e+000, 3.21961006e-105, 3.12350306e-105, ...,
        3.02873870e-105, 3.62721220e-105, 3.12722169e-105],
       ...,
       [3.24365359e-005, 0.00000000e+000, 3.09270077e-005, ...,
        0.00000000e+000, 0.00000000e+000, 2.96285088e-005],
       [3.24370880e-005, 0.00000000e+000, 3.09275341e-005, ...,
        3.06269679e-005, 2.83180664e-005, 2.96290131e-005],
       [0.00000000e+000, 0.00000000e+000, 3.09276105e-005, ...,
        0.00000000e+000, 2.83181363e-005, 2.96290863e-005]]), 'logl': array([  1.02037311,   1.02241572,   1.04127719, ..., 242.99996044,
       242.99997746, 242.99997993])}, 'samples': array([[18.77634936, 18.90750809],
       [12.60924515, 25.10544119],
       [18.83860508, 18.82276784],
       ...,
       [12.48040023, 12.52200348],
       [ 6.44782679, 18.79938972],
       [31.28896622, 18.64627503]]), 'maximum_likelihood': {'logl': 242.99997993314864, 'point': [25.1321140325712, 12.566315775893539], 'point_untransformed': [0.7999800357265787, 0.3999982544374246]}, 'ncall': 44127, 'paramnames': ['x0', 'x1'], 'logzerr_single': 0.12513581276265934, 'insertion_order_MWW_test': {'independent_iterations': inf, 'converged': True}}
As you can see there is one key for 'ess' !

**Comment by Joshuaalbert** [comment]
I explore hyperparameters for both num_live_points=None (Reactive) and non-zero (Static). So far, the reactive sampler performs worse than it's static version actually, fyi.

**Comment by Joshuaalbert** [comment]
Try with these params:

```
"params": {
    "min_num_live_points": 150
  }
  ```
  
  and these params:
  
  ```
  "params": {
    "num_live_points": 150
  }
  ```

**Comment by rruizdeaustri** [comment]
The problem is that with the static one ultranest does not compute the ess as far as I know.

**Comment by Joshuaalbert** [comment]
That's not good. The static one performs best so far. Can you dig it out of the ultranest code? I'll post an issue to its github asking for it.

**Comment by rruizdeaustri** [comment]
Ok, I'll do it.

**Comment by Joshuaalbert** [comment]
Btw, I posted here https://github.com/JohannesBuchner/UltraNest/issues/122

**Comment by rruizdeaustri** [comment]
BTW do you still have problems with nautilus and the ESS computation ?

**Comment by JohannesBuchner** [comment]
Hi all, you should never use `ultranest.NestedSampler`, it is for testing a basic algorithm only. It lacks many features.

If you want to avoid reactive/dynamic nested sampling behaviour, set `max_num_improvement_loops=0` when running the `ReactiveNestedSampler`.

**Comment by JohannesBuchner** [comment]
In that case, `min_num_live_points` is the (fixed) number of live points.

**Comment by Joshuaalbert** [comment]
Thanks @JohannesBuchner we were using it wrongly then, but now it's correct :)

**Comment by Joshuaalbert** [comment]
@rruizdeaustri yes, Nautilus is also running.
